# ============================================================================
# ADMIN-SERVICE CONFIGURATION
# ============================================================================

server:
  port: ${SERVER_PORT:8088}

spring:
  application:
    name: ADMIN-SERVICE

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${ADMIN_DB:admin_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

logging:
  level:
    com.microServiceTut.admin_service: DEBUG
