# ============================================================================
# API-GATEWAY SERVICE CONFIGURATION
# ============================================================================

server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Auth Service - PUBLIC (no JWT required)
            - id: auth-service
              uri: lb://USER-AUTH-SERVICE
              predicates:
                - Path=/auth/**

            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/orders/**

            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/api/payments/**

            - id: menu-service
              uri: lb://MENU-SERVICE
              predicates:
                - Path=/api/menus/**

            - id: restaurant-service
              uri: lb://RESTAURANT-SERVICE
              predicates:
                - Path=/api/restaurants/**

            - id: cart-service
              uri: lb://CART-SERVICE
              predicates:
                - Path=/api/cart/**

            - id: delivery-service
              uri: lb://DELIVERY-SERVICE
              predicates:
                - Path=/api/delivery/**

            - id: admin-service
              uri: lb://ADMIN-SERVICE
              predicates:
                - Path=/api/admin/**

            # Notification Service
            - id: notification-service
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/api/notifications/**

# JWT Configuration - MUST match User-Auth-Service secret
jwt:
  secret: ${JWT_SECRET:mySecretKeyForJWTTokenGenerationWhichShouldBeAtLeast256BitsLongForHS256Algorithm2024}

logging:
  level:
    com.microServiceTut.api_gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
