# ============================================================================
# CART-SERVICE CONFIGURATION
# ============================================================================

server:
  port: 8085

spring:
  application:
    name: CART-SERVICE

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${CART_DB:cart_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1122334455}

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
