# ============================================================================
# ORDER-SERVICE CONFIGURATION
# ============================================================================

server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: ORDER-SERVICE

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${ORDER_DB:order_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      paymentCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    instances:
      paymentRetry:
        maxAttempts: 3
        waitDuration: 1s

  timelimiter:
    instances:
      paymentTimeLimiter:
        timeoutDuration: 2s

  ratelimiter:
    instances:
      paymentRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 10s

  bulkhead:
    instances:
      paymentBulkhead:
        maxConcurrentCalls: 3

logging:
  level:
    com.microServiceTut.order_service: DEBUG
    io.github.resilience4j.circuitbreaker: DEBUG
