# ============================================================================
# PAYMENT-SERVICE CONFIGURATION
# ============================================================================

server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: PAYMENT-SERVICE

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${PAYMENT_DB:payment_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

logging:
  level:
    com.microServiceTut.payment_service: DEBUG
