# ============================================================================
# RESTAURANT-SERVICE CONFIGURATION
# ============================================================================

server:
  port: ${SERVER_PORT:8086}

spring:
  application:
    name: RESTAURANT-SERVICE

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${RESTAURANT_DB:restaurant_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  # Redis Cache Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  cache:
    type: ${CACHE_TYPE:simple}

logging:
  level:
    com.microServiceTut.restaurant_service: DEBUG
